- name: Repository Dispatch
  uses: peter-evans/repository-dispatch@v1
  with:
    token: ${{ secrets.REPO_ACCESS_TOKEN }}
    repository: YashJipkate/sample-dispatch-event-consumer
    event-type: dispatch-event
    client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

